import Form from '@/components/form';
import Table from '@/components/table';
import Head from 'next/head'
import { useState } from 'react';
 
import { BiUserPlus } from "react-icons/bi";
export default function Home() {


const [visible,setvisible] = useState(false);


const addForm =()=>{
  setvisible(!visible)
}
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5 container mx-auto">
      <h1 className="text-2xl font-bold text-center ">
        Empolyee management 
       </h1>

       <div className="container mx-auto border-b py-5 flex justify-between">
       <div className="left flex gap-3">
      <button onClick={addForm}  className="flex  bg-indigo-500 rounded-sm px-5 py-2   text-white hover:bg-indigo-600 duration-100">
        Add Employee  <span className="px-1"><BiUserPlus size={23}></BiUserPlus></span>
        </button>
       </div>
       </div>


{visible?<Form></Form>:<></>}
 

 <Table></Table>
      </main>
    </>
  )
}
